### ISSUE TITLE
Relay chaining

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/hutch-relay#38]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Because Relay compatibly implements a subset of the Task API spec, it should be possible to connect a Relay Upstream to another Relay.

This issue captures the work needed to make that a reality.

Known blockers at time of writing:

- #14 
- Relay uses a "unified" queue system Downstream, but Upstream it complies with the Task API spec and makes separate queue requests for separate Task types (a, b, c).
    - In order for a Relay to poll another Relay, we need to do either (or both) of:
        - support polling unified queues Upstream
            - we could do this in configuration somewhat similar to how Bunny does
        - support typed queues Downstream (more compliant with the Task API spec, but arguably complicates Bunny (or other Relay compatible downstream clients) deployments)
- ...? There may be other stuff we haven't noticed yet that blocks this

### Acceptance Criteria

- [ ] Relay can be chained to another Relay
    - [ ] end to end test of `Rquest -> Relay -> Relay -> Bunny`
- [ ] Documentation added.

<details>
<summary>Sample compose file for the end to end test</summary>

```yaml

name: hutch-relay-dev

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data:Z

  adminer:
    image: wodby/adminer
    depends_on:
      - db
    restart: always
    ports:
      - 9000:9000
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DESIGN: pepa-linha

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  relay:
    build:
      dockerfile: app/Hutch.Relay/Dockerfile
    restart: always
    depends_on:
      - db
      - rabbitmq
    environment:
      DOTNET_Environment: Development
      ConnectionStrings__Default: Server=host.docker.internal;Port=5432;Database=hutch-relay;User Id=postgres;Password=postgres
      RelayTaskQueue__ConnectionString: amqp://user:password@rabbitmq:5672
      Obfuscation__LowNumberSuppressionThreshold: 0
      Obfuscation__RoundingTarget: 0

      UpstreamTaskApi__BaseUrl: <REDACTED>
      UpstreamTaskApi__CollectionId: <REDACTED>
      UpstreamTaskApi__Username: <REDACTED>
      UpstreamTaskApi__Password: <REDACTED>

  relay2:
    build:
      dockerfile: app/Hutch.Relay/Dockerfile
    restart: always
    depends_on:
      - relay
      - db
      - rabbitmq
    environment:
      DOTNET_Environment: Development
      ConnectionStrings__Default: Server=host.docker.internal;Port=5432;Database=hutch-relay-2;User Id=postgres;Password=postgres
      RelayTaskQueue__ConnectionString: amqp://user:password@rabbitmq:5672
      Obfuscation__LowNumberSuppressionThreshold: 0
      Obfuscation__RoundingTarget: 0

      UpstreamTaskApi__BaseUrl: http://relay:8080
      UpstreamTaskApi__CollectionId: 0195663f-f813-791a-9ac4-e7efaa3377bc
      UpstreamTaskApi__Username: relay2
      UpstreamTaskApi__Password: 'U$$xTwA8fj$$#pOPll'
  bunny:
    image: ghcr.io/health-informatics-uon/hutch/bunny:edge
    restart: always
    depends_on:
      - relay2
      - rabbitmq
    environment:
      DATASOURCE_DB_USERNAME: postgres
      DATASOURCE_DB_PASSWORD: postgres
      DATASOURCE_DB_DATABASE: hutch-omop
      DATASOURCE_DB_DRIVERNAME: postgresql
      DATASOURCE_DB_SCHEMA: public
      DATASOURCE_DB_PORT: 5432
      DATASOURCE_DB_HOST: host.docker.internal
      TASK_API_BASE_URL: http://relay2:8080/link_connector_api
      TASK_API_USERNAME: bunny
      TASK_API_PASSWORD: '!XSDpwnRUs*wv88$$'
      TASK_API_TYPE:
      LOW_NUMBER_SUPPRESSION_THRESHOLD:
      ROUNDING_TARGET:
      POLLING_INTERVAL: 5
      COLLECTION_ID: 01956640-fbd1-775c-80c0-de93f8e43c05

volumes:
  pgdata:

```
</details>

To use the above the following setup is needed:
1. Load omop data into `hutch-omop` in the postgres server. Use e.g. https://github.com/health-informatics-uon/omop-lite
2. Run db migrations for each relay instance
    - e.g. using `dotnet run` or `docker run` and `database update --connection-string <CORRECT RELAY CONNECTION STRING>` 
3. Add users/collections to each relay instance
    - e.g. using `dotnet run` or `docker run` and `users add <relay2|bunny> --connection-string <CORRECT RELAY CONNECTION STRING>` 
    - use the correct username when adding to each Relay and then update the password and collection id for `relay2` and `bunny`.

### Confirm creation

- [x] This issue is ready
